title: Dr. Narender Kumar
email: your@email.com
description: "Physician, Researcher, Harvard Alumnus"
baseurl: ""
url: "https://drnarenderkumar.github.io"
theme: minima
sass:
  style: assets/css/style.scss

# Navigation
header_pages:
  - index.md
  - about.md
  - publications.md
  - cv.md
  - contact.md
