title: Dr. Narender Kumar
email: narender@alumni.harvard.edu
description: "Physician, Researcher, Harvard Alumnus, Marie Sk≈Çodowska-Curie Fellow"
baseurl: ""
url: "https://drnarenderkumar.github.io"
theme: minima
sass:
  style: assets/css/style.scss

# Navigation
header_pages:
  - index.md
  - about.md
  - awards.md
  - publications.md
  - conferences.md
  - contact.md
