title: Dr. Narender Kumar
email: your@email.com
description: "Physician, Researcher, Harvard Alumnus"
baseurl: ""    # leave blank for a user site
url: "https://drnarenderkumar.github.io"
theme: minima   # minimal builtâ€‘in theme
