title: Dr. Narender Kumar
email: narender@alumni.harvard.edu

baseurl: ""
url: "https://drnarenderkumar.github.io"
theme: minima
sass:
  style: assets/css/style.scss

# Navigation
header_pages:
  - about.md
  - awards.md
  - publications.md
  - conferences.md
  - contact.md
